#[static_party_stat_page]
#sora = 0x2DE9360
#[static_stat_page]
#sora = 0x2D5CC10
#[stat_page]
#first_stat_page_pointer = 0x2D5CB10

# character attributes size: 0x74
[attributes]
sora = 0x2DE9364
donald = 0x2DE93D8
goofy = 0x2DE944C
tarzan = 0x2DE94C0
#unknown = 0x2DE9534
aladdin = 0x2DE95A8
ariel = 0x2DE961C
jack = 0x2DE9690
peter_pan = 0x2DE9704
beast = 0x2DE9778

[party]
shared_abilities = 0x2DE98F9
magic_tiers = 0x2DE97F2
exp_multiplier = 0x2D5CB00
lvlup_tables = 0x2D267FE

[inventory]
item_stock = 0x2DE97F9
gummi_stock = 0x2DF51D8
munny = 0x2DFF77C

[item]
stats = 0x2D24798
names = 0x2D23014 # 4to8 Pointer

[scene]
loaded_gameobjects = 0x2D59D30

[events]
on_attack = { address = 0x2B2DC0, size = 5 } # rbx = command_stats_pointer, rcx = gameobject_address
on_get_hit = { address = 0x2A49C5, size = 3 } # rbx = new current_hp, rsi = gameobject_address, rax = party_stat_page_address, rdi = stat_page_address, 255 - r14 = damage, rdx = 4to8Base
on_get_reward = { address = 0x2B55E6, size = 3 } # rcx = reward_id

[memory]
base_4to8 = 0x2EE3980
# on_open_chest = 0x284B94 # [rbx = item_id]
# on_open_chest_size = 3
# on_open_chest_successful = 0xD429F
# on_open_chest_successful_size = 4