name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build Solution
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . --config Release
    - name: Copy Artifacts
      run: |
        mkdir artifacts
        cp build/Release/DBGHELP.dll artifacts
        cp build/external/subproject/lua544/Release/lua54.dll artifacts
        cp config/LuaBackend.toml artifacts
    - name: Copy DINPUT8 Artifacts
      run: |
        mkdir artifacts-dinput8
        cp build/Release/DINPUT8.dll artifacts-dinput8
        cp build/external/subproject/lua544/Release/lua54.dll artifacts-dinput8
        cp config/LuaBackend.toml artifacts-dinput8
    - name: Upload DBGHELP
      uses: actions/upload-artifact@v3
      with:
        name: DBGHELP
        path: artifacts
    - name: Upload DINPUT8
      uses: actions/upload-artifact@v3
      with:
        name: DINPUT8-linux
        path: artifacts-dinput8
