name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build Solution
      run: msbuild /m /p:Configuration=Debug /NODEFAULTLIB:library
    - name: Upload DINPUT8
      uses: actions/upload-artifact@v2
      with:
        name: DINPUT8
        path: |
          x64/Debug/DINPUT8.dll
