name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build Solution
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . --config Release
    - name: Copy Artifacts
      run: |
        mkdir artifacts
        cp build/Release/DBGHELP.dll artifacts
        cp dll/discord-rpc.dll artifacts
        cp dll/Lua.dll artifacts
        cp config/LuaBackend.toml artifacts
    - name: Upload DBGHELP
      uses: actions/upload-artifact@v2
      with:
        name: DBGHELP
        path: artifacts
