name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build Solution
      run: |
        mkdir build && cd build
        cmake .. -DPROGRAM_VERSION:STRING="${{github.ref_name}}"
        cmake --build . --config Release
    - name: Compress Artifacts
      run: |
        7z a DBGHELP.zip ./build/Release/DBGHELP.dll ./build/external/subproject/lua544/Release/lua54.dll ./config/LuaBackend.toml
    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        files: |
          DBGHELP.zip
